# this corresponds to the default config
# MODEL:
#   WEIGHTS: /fp/projects01/ec35/homes/ec-thallesss/representation_learning/src/methods/dinov2/experiments/run0/
train:
  dataset_path: ImageNet:split=TRAIN
  batch_size_per_gpu: 256
  centering: "centering"
  output_dir: ./experiments/run1
student:
  block_chunks: 4
  arch: vit_base
ibot:
  separate_head: true