# this corresponds to the default config
# MODEL:
#   WEIGHTS: /fp/projects01/ec35/homes/ec-thallesss/representation_learning/src/methods/dinov2/experiments/run0/
train:
  dataset_path: ImageNet:split=TRAIN
  batch_size_per_gpu: 256
  centering: ""
  output_dir: ./experiments/run0
student:
  block_chunks: 4
  arch: vit_base
ibot:
  separate_head: true
carp:
  class_partition_size: 4096
  patch_partition_size: 512
  class_num_tasks: 4
  patch_num_tasks: 4
  num_class_experts: 8
  num_patch_experts: 1
  class_memory_size: 65536
  patch_memory_size: 8192
  head_bottleneck_dim: 256
  